README.md, examples/invoice.js, examples/receipt.js, mindee/api/receipt.js, mindee/api/request.js, mindee/inputs.js, tests/input.js
Add possibility to use readable streams as inputs
- Add stream as input
- Update request code to handle streams with API
- Update input to handle streams
- Add stream in documentation and example
- Add unit test for stream input using Readable Stream
See #27
=> Add streams into inputs

.gitignore, CHANGELOG.md, README.md, mindee/api/object.js, mindee/api/request.js, mindee/documents/invoice.js, mindee/documents/receipt.js
Fixed include_mvision error to get all words, and type attribute for CompanyNumber field in invoice
see #29 and #30
=> Fix #29 #30

CHANGELOG.md, mindee/api/invoice.js, mindee/api/receipt.js, mindee/documents/document.js, mindee/documents/fields/amount.js, mindee/documents/fields/date.js, mindee/documents/fields/locale.js, mindee/documents/fields/orientation.js, mindee/documents/fields/paymentDetails.js, mindee/documents/fields/tax.js, package.json
Corrected parameters error in _request method, reconstruction method was also setting fields to the probability value of the highest probality field instead of the field itself. Minor changes on pageNumber default value.
=> fix: :bug: fixed reconstruction bugs

README.md
When trying the SDK locally, I found an error in the first sample code found in the README.
=> fix: :pencil: updating README.md first code example

package.json
=> chg: :hammer: fix app path

package-lock.json
=> fix SDK version

CHANGELOG.md, mindee/api/financialDocument.js, mindee/api/object.js, mindee/api/request.js, mindee/api/response.js, mindee/documents/fields/field.js, mindee/documents/financialDocument.js, mindee/documents/invoice.js, mindee/documents/receipt.js, package.json, tests/api/apiObject.js, tests/data/api/invoice/v2/invoice.json, tests/data/api/invoice/v2/invoice_all_na.json, tests/data/api/receipt/v3/receipt.json, tests/data/api/receipt/v3/receipt_all_na.json, tests/documents/financialDocument.js, tests/documents/invoice.js, tests/documents/receipt.js, tests/fields/field.js
Breaking change SDK adaptation for the new Mindee API V2 response scheme.
All adaptations required to use the Mindee's new API response scheme. That includes document classes, unit tests, and HTTP client.
Tested by mocking API responses on 12k documents (receipts and invoices).
Adapted all the existing unit tests with the new features.
=> :sparkles: Mindee API V2 support

.github/workflows/license.yml, .github/workflows/linting.yml, .github/workflows/test.yml, README.md, mindee/api/response.js, mindee/documents/financialDocument.js, package-lock.json, package.json
Update actions to run unit tests on all Node.js LTS versions
Users may be on different Node.js versions
Tested in Github actions.
=> chg: :construction_worker: run unit tests on all LTS versions

CHANGELOG.md, package-lock.json, package.json
1. Add the following new fields in the Invoice and financial document object to be Invoice API V3 compliant:
- supplierAddress
- customerName
- customerAddress
- customerCompanyRegistration
2. Change testing process to be able to use files from the current branch instead of files from the Mindee SDK already deployed.
3. Change the way to get the bbox and the probability values to match with the V3 API
=> chg: 📝 prepare v1.1.2

.github/workflows/test.yml
=> :white_check_mark: add node18 to tests

CHANGELOG.md
=> version 1.3.1

CHANGELOG.md, mindee/inputs.js, package-lock.json, package.json
=> Version 1.4.0

.npmignore, package.json
We should use the `files` section of the `package.json` to specify the files to include in the NPM package.
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files
=> Remove all unneccessary files from the NPM package

CHANGELOG.md, package-lock.json, package.json
=> version 2.1.0

CHANGELOG.md, package-lock.json, package.json, src/api/endpoint.ts
:bug: fix for sending base64 documents.
Manual testing of various ways of sending files.
=> Version 2.1.1

src/inputs/index.ts, tests/api/response.spec.ts, tests/documents/cropper/cropperV1.spec.ts, tests/documents/customDocument.spec.ts, tests/documents/financialDocument/financialDocumentV1.spec.ts, tests/documents/invoice/invoiceV3.spec.ts, tests/documents/passport/passportV1.spec.ts, tests/documents/receipt/receiptV3.spec.ts, tests/documents/receipt/receiptV4.spec.ts, tests/fields/cropper.spec.ts, tests/inputs/input.spec.ts, tests/pdf/pdfOperation.spec.ts
Run automated linting on tests directory.
=> :rotating_light: lint the unit test code

README.md, src/documents/receipt/receiptV4.ts, tests/documents/receipt/receiptV4.spec.ts
Fix for `supplier` property of ReceiptV4 document which was incorrectly called `merchantName`
Added better unit tests.
=> :bug: Fix for supplier property in ReceiptV4.

README.md, src/client.ts, src/inputs/base.ts, src/inputs/index.ts, src/inputs/sources.ts, tests/inputs/pageOperations.spec.ts, tests/inputs/sources.spec.ts
Add buffer input source.
#101 
Added unit test
=> :sparkles: add buffer input source

src/cli.ts, src/client.ts, src/documents/fr/idCard/idCardV1.ts, src/documents/index.ts, src/fields/field.ts, src/index.ts, tests/apiPaths.ts, tests/documents/fr/idCard/idCardV1.spec.ts
* :sparkles: Add support for French ID cards.
https://github.com/mindee/mindee-api-nodejs/issues/105
=> :sparkles:  Add support for French ID cards.

CHANGELOG.md, package-lock.json, package.json
* :sparkles:  Add support for French ID cards.
* :sparkles: add buffer input source
=> :bookmark: version 3.1.0

src/documents/fr/idCard/idCardV1.ts, src/documents/invoice/invoiceV3.ts, src/documents/passport/passportV1.ts, src/documents/receipt/receiptV3.ts, src/fields/amount.ts, src/fields/apiBuilder.ts, src/fields/companyRegistration.ts, src/fields/field.ts, src/fields/locale.ts, src/fields/orientation.ts, src/fields/paymentDetails.ts
- :memo: Comment the response objects
=> :memo: Comment the response objects

src/client.ts
Parameter definitions for public methods should be exported and documented properly.
=> :memo: Export and add comments for method parameters.

src/cli.ts, src/client.ts, src/documents/fr/bankAccountDetails/bankAccountDetailsV1.ts, src/documents/fr/index.ts, tests/apiPaths.ts, tests/documents/fr/bankAccountDetails/bankAccountDetailsV1.spec.ts
- :sparkles: Add support for FR Bank Account Details V1.
=> :sparkles: Add support for FR Bank Account Details V1

README.md, src/cli.ts, src/client.ts, src/documents/fr/carteVitale/carteVitaleV1.ts, src/documents/fr/index.ts, src/documents/fr/socialSecurityCard/socialSecurityCardV1.ts, tests/apiPaths.ts, tests/documents/fr/carteVitale/carteVitaleV1.spec.ts, tests/documents/fr/socialSecurityCard/socialSecurityCardV1.spec.ts
- :sparkles: Add support for Carte Vitale V1
=> :sparkles: Add support for Carte Vitale V1

src/cli.ts, src/client.ts, src/documents/index.ts, src/documents/shipping_container/shippingContainerV1.ts, src/documents/shipping_containers/shippingContainerV1.ts, src/index.ts, tests/apiPaths.ts, tests/documents/shippingContainer/shippingContainerV1.spec.ts
- :sparkles: Add support for shipping container API V1
=> ✨ Add support for shipping container API V1

CHANGELOG.md, package-lock.json, package.json
=> 📝 : version 3.2.0

src/api/endpoint.ts
✨  An env variable can be used to change the Mindee base API url
=> ✨  An env variable can be used to change the Mindee base API url

src/documents/cropper/cropperV1.ts, src/documents/eu/licensePlate/licensePlateV1.ts, src/documents/fr/carteVitale/carteVitaleV1.ts, src/documents/invoice/invoiceLineItem.ts, src/documents/invoice/invoiceV4.ts, src/documents/passport/passportV1.ts, src/documents/shipping_container/shippingContainerV1.ts, src/fields/amount.ts, tests/fields/amount.spec.ts, tests/fields/tax.spec.ts
Minor changes in the summaries.
=> :sparkles: Minor changes in the summaries

src/documents/receipt/receiptV4.ts, src/documents/receipt/tax.ts
:sparkles: Support Receipt V4.1
:boom: Updating "Basis" property in ReceiptV4 to "Base"
=> ✨ Support Receipt V4.1

src/documents/invoice/invoiceV4.ts, tests/apiPaths.ts
=> ✨ Support Invoice V4.1

README.md
=> :memo: add shield badges

src/documents/eu/licensePlate/licensePlateV1.ts, src/documents/fr/bankAccountDetails/bankAccountDetailsV1.ts, src/documents/fr/carteVitale/carteVitaleV1.ts, src/documents/fr/idCard/idCardV1.ts, src/documents/passport/passportV1.ts, src/documents/receipt/receiptV4.ts, src/documents/us/bankCheck/bankCheckV1.ts, tests/documents/fr/carteVitale/carteVitaleV1.spec.ts
Updates to documentation
Fix for social security field name in Carte Vitale
=> :memo: updates to class documentation

src/cli.ts, src/client.ts, src/documents/index.ts, src/documents/invoiceSplitter/invoiceSplitterV1.ts, tests/apiPaths.ts, tests/documents/invoiceSplitter/invoiceSplitterV1.spec.ts
:sparkles: Add invoice splitter support (beta)
Unit test added
=> :sparkles: Add invoice splitter support (beta)

src/cli.ts, src/client.ts, src/documents/index.ts, src/documents/mindeeVision/mindeeVisionV1.ts, tests/apiPaths.ts, tests/documents/mindeeVision/mindeeVisionV1.spec.ts
Add support for the mindee_vision API (for internal testing).
Unit tests added.
=> :sparkles: add mvision support

src/documents/eu/licensePlate/licensePlateV1.ts, src/documents/fr/bankAccountDetails/bankAccountDetailsV1.ts, src/documents/invoiceSplitter/invoiceSplitterV1.ts, src/documents/proofOfAddress/proofOfAddressV1.ts, src/documents/shippingContainer/shippingContainerV1.ts, src/fields/classification.ts, tests/apiPaths.ts, tests/documents/custom/lineItems.spec.ts, tests/documents/invoiceSplitter/invoiceSplitterV1.spec.ts
Update test data files.
Minor changes to string output of documents.
Added `confidence` property to invoice splitter beta.
Unit tests updated
=> :up_arrow: update test files, minor updates to string output

CHANGELOG.md, package-lock.json, package.json
* :sparkles: add support for asynchronous predictions
* :sparkles: add **experimental** support for line items in custom documents
* :art: harmonize bbox and bounding box terminology
* :arrow_up: update test files, minor updates to string output
* :label: classification fields are always strings
* :bug: fix error message for missing API key, document type may be undefined
=> :bookmark: Version 3.7.0

package-lock.json, package.json, src/logger.ts
=> :arrow_up: upgrade to TypeScript 5.0.3

.github/workflows/docs.yml, .github/workflows/publish.yml, .github/workflows/test-code-samples.yml, .gitignore, README.md, docs/code_samples/bank_account_details_v1.txt, docs/code_samples/bank_check_v1.txt, docs/code_samples/carte_vitale_v1.txt, docs/code_samples/cropper_v1.txt, docs/code_samples/custom_v1.txt, docs/code_samples/expense_receipts_v4.txt, docs/code_samples/financial_document_v1.txt, docs/code_samples/idcard_fr_v1.txt, docs/code_samples/invoices_v4.txt, docs/code_samples/license_plates_v1.txt, docs/code_samples/passport_v1.txt, docs/code_samples/proof_of_address_v1.txt, docs/code_samples/shipping_containers_v1.txt, package-lock.json, package.json, src/index.ts, tests/test_code_samples.sh
* Add code samples for Platform docs.
* Execute sample code for testing.
=> Add code samples

src/cli.ts, tests/test_code_samples.sh
* :white_check_mark: minor improvements to tests
* :bug: fix for options not being passed properly in the CLI tool
=> :white_check_mark: minor improvements to tests

docs/code_samples/default.txt, tests/test_code_samples.sh
Add default code sample for when we don't support the API directly.
=> :white_check_mark: add default code sample

docs/code_samples/invoice_splitter_v1_async.txt
Document Invoice Splitter v1. Use this as a template for future async calls.
=> :memo: add Invoice Splitter v1 sample code

.eslintrc, .gitignore, src/documents/financialDocument/financialDocumentV1.ts, src/documents/invoice/invoiceV3.ts, src/documents/invoice/invoiceV4.ts, src/documents/receipt/receiptV3.ts, src/documents/receipt/receiptV4.ts, src/documents/us/bankCheck/bankCheckV1.ts, src/fields/amount.ts, tests/fields/amount.spec.ts, tests/test_code_samples.sh
Simplify use of the `Amount` class init, in almost all cases there is no need to change the value key.
Updated unit test.
=> Simplify amount field

package-lock.json, package.json, tsconfig.json
Update to latest version of typescript
=> :arrow_up: update typescript

src/documents/financialDocument/financialDocumentV1.ts, src/documents/financialDocument/financialDocumentV1LineItem.ts, src/documents/receipt/receiptV5.ts, src/documents/receipt/receiptV5LineItem.ts, src/fields/locale.ts, src/fields/tax.ts, tests/documents/financialDocument/financialDocumentV1.spec.ts, tests/fields/locale.spec.ts
Autogenerated support for financial docs v1.1
=> Financial docs v1.1

src/documents/documentConfig.ts
Update handling of HTTP return codes to be more permissive.
This allows a bit more flexibility for the back-end team.
=> :recycle: change http status code handling for async requests

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 3.9.0

docs/code_samples/bank_account_details_v2.txt, src/client.ts, src/documents/fr/bankAccountDetails/bankAccountDetailsV2.ts, src/documents/fr/bankAccountDetails/bankAccountDetailsV2Bban.ts, src/documents/fr/index.ts, src/documents/receipt/receiptV5.ts, src/documents/receipt/receiptV5LineItem.ts, tests/documents/fr/bankAccountDetails/bankAccountDetailsV2.spec.ts
- :sparkles: Add support for FR Bank Details V2
- :arrow_up: Update testing lib
- :recycle: Update Receipt V5 to match newer format
=> :sparkles: add support for FR Bank Details V2

src/api/endpoint.ts
Provide better error logging.
Tested locally with mock server.
=> :loud_sound: better logging of JSON errors

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 3.10.2

docs/bank_account_details_v2.md, docs/bank_check_v1.md, docs/carte_vitale_v1.md, docs/custom_v1.md, docs/expense_receipts_v5.md, docs/financial_document_v1.md, docs/idcard_fr_v1.md, docs/invoice_splitter_v1.md, docs/invoices_v4.md, docs/license_plates_v1.md, docs/passport_v1.md, docs/proof_of_address_v1.md, docs/us_driver_license_v1.md
=> :memo: doc quickfixes

docs/invoice_splitter_v1.md, package.json
- :wrench: fix husky blocking publish action by only enabling it during `preinstall`
- :memo: fix typo in doc
=> :wrench: tweak pre-commit hook behavior

.husky/pre-commit, package-lock.json, package.json
- :bug: remove husky to avoid install conflicts
=> :bug: remove husky pre-commit hook

package.json
- :recycle: restore former linting rules
=> :recycle: restore lint-fix

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.0.2

.github/workflows/license.yml, .github/workflows/linting.yml, .github/workflows/publish.yml, .github/workflows/test-code-samples.yml, .github/workflows/test.yml, .mocharc.json, package-lock.json, package.json
* :arrow_up: upgrade support for node 20
* :coffin: removed support for node<16
=> :boom: upgrade node support

tests/api/response.spec.ts, tests/inputs/pageOperations.spec.ts, tests/inputs/sources.spec.ts, tests/pdf/pdfOperation.spec.ts, tests/product/cropper/cropperV1.spec.ts, tests/product/custom/customDocument.spec.ts, tests/product/custom/lineItems.spec.ts, tests/product/eu/licensePlate/licensePlateV1.spec.ts, tests/product/financialDocument/financialDocumentV1.spec.ts, tests/product/fr/bankAccountDetails/bankAccountDetailsV1.spec.ts, tests/product/fr/bankAccountDetails/bankAccountDetailsV2.spec.ts, tests/product/fr/carteVitale/carteVitaleV1.spec.ts, tests/product/fr/idCard/idCardV1.spec.ts, tests/product/invoice/invoiceV4.spec.ts, tests/product/invoiceSplitter/invoiceSplitterV1.spec.ts, tests/product/ocr/ocr.spec.ts, tests/product/passport/passportV1.spec.ts, tests/product/proofOfAddress/proofOfAddressV1.spec.ts, tests/product/receipt/receiptV4.spec.ts, tests/product/receipt/receiptV5.spec.ts, tests/product/us/bankCheck/bankCheckV1.spec.ts, tests/product/us/driverLicense/driverLicenseV1.spec.ts, tests/test_code_samples.sh
=> :arrow_up: update testing lib syntax

docs/code_samples/invoice_splitter_v1_async.txt, docs/invoice_splitter_v1.md, src/cli.ts, src/client.ts
* :sparkles: add support for async auto-poll
* :boom: simplify CLI syntax
=> :sparkles: add async auto-poll support

src/parsing/common/document.ts, tests/product/ocr/ocr.spec.ts
* :bug: fix issue where ocr object wasn't properly initialized
=> :bug: fix ocr

docs/bank_account_details_v2.md, docs/bank_check_v1.md, docs/carte_vitale_v1.md, docs/cropper_v1.md, docs/custom_v1.md, docs/expense_receipts_v5.md, docs/financial_document_v1.md, docs/idcard_fr_v1.md, docs/invoice_splitter_v1.md, docs/invoices_v4.md, docs/license_plates_v1.md, docs/passport_v1.md, docs/proof_of_address_v1.md, docs/us_driver_license_v1.md
=> :memo: update md examples path

docs/code_samples/us_w9_v1.txt, docs/us_w9_v1.md, src/http/error.ts, src/parsing/standard/position.ts, src/product/us/index.ts, src/product/us/w9/w9V1.ts, src/product/us/w9/w9V1Document.ts, src/product/us/w9/w9V1Page.ts, tests/product/us/w9/w9V1.spec.ts
=> :sparkles: add support for w9

README.md, docs/code_samples/multi_receipts_detector_v1.txt, docs/multi_receipts_detector_v1.md, docs/us_w9_v1.md, src/product/index.ts, src/product/internal.ts, src/product/multiReceiptsDetector/internal.ts, src/product/multiReceiptsDetector/multiReceiptsDetectorV1.ts, src/product/multiReceiptsDetector/multiReceiptsDetectorV1Document.ts, tests/product/multiReceiptsDetector/multiReceiptsDetectorV1.spec.ts
Waiting for API changes before merge.
=> :sparkles: add support for multi receipts detector

src/parsing/standard/position.ts, tests/product/multiReceiptsDetector/multiReceiptsDetectorV1.spec.ts
=> :bug: fix missing position field displays

docs/code_samples/cropper_v1.txt, docs/cropper_v1.md, docs/financial_document_v1.md, src/client.ts, tests/product/cropper/cropperV1.spec.ts, tests/product/eu/licensePlate/licensePlateV1.spec.ts, tests/product/fr/bankAccountDetails/bankAccountDetailsV1.spec.ts, tests/product/fr/bankAccountDetails/bankAccountDetailsV2.spec.ts, tests/product/fr/carteVitale/carteVitaleV1.spec.ts, tests/product/fr/idCard/idCardV1.spec.ts, tests/product/fr/idCard/idCardV2.spec.ts, tests/product/passport/passportV1.spec.ts, tests/product/proofOfAddress/proofOfAddressV1.spec.ts, tests/product/receipt/receiptV5.spec.ts, tests/product/us/bankCheck/bankCheckV1.spec.ts, tests/product/us/driverLicense/driverLicenseV1.spec.ts, tests/product/us/w9/w9V1.spec.ts
* :bug: fix asynchronous timer suddenly crashing if no timer parameters were provided
* :recycle: update syntaxes & fix typos
=> :bug: fix async timer crashing

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.2.0

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.3.0

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.3.1

package-lock.json, package.json, src/parsing/common/extras/cropperExtra.ts, src/parsing/common/extras/extras.ts, src/parsing/custom/listField.ts, src/product/invoiceSplitter/invoiceSplitterV1Document.ts, src/product/invoiceSplitter/invoiceSplitterV1PageGroup.ts
* :arrow_up: upgrade chai to latest version
* :recycle: minor refactoring
=> :arrow_up: dependency upgrade & minor refactoring

docs/code_samples/invoices_v4.txt, docs/financial_document_v1.md, docs/invoices_v4.md, docs/us_w9_v1.md, src/cli.ts, src/client.ts, src/http/apiSettings.ts, src/http/baseEndpoint.ts, src/http/endpoint.ts, src/http/error.ts, src/http/index.ts, src/parsing/common/asyncPredictResponse.ts, src/parsing/common/feedback/feedbackResponse.ts, src/parsing/common/index.ts, src/parsing/common/predictResponse.ts, src/product/financialDocument/financialDocumentV1Document.ts, src/product/invoice/invoiceV4.ts, src/product/invoice/invoiceV4Document.ts, src/product/invoice/invoiceV4LineItem.ts, src/product/us/w9/w9V1.ts, src/product/us/w9/w9V1Document.ts, src/product/us/w9/w9V1Page.ts, tests/api/feedbackResponse.spec.ts, tests/product/invoice/invoiceV4.spec.ts, tests/product/us/w9/w9V1.spec.ts
* Add a basic feedback endpoint.
* Add ability to get previously parsed documents.
* Some cleanup.
=> :sparkles: add feedback and fetch endpoints

docs/getting_started.md, src/parsing/common/extras/extras.ts, src/parsing/common/inference.ts
* :bug: fix display issues when products didn't have pages
* :recycle: update invoice splitter
* :memo: fix doc typos
=> :bug: invoice splitter fixes

src/parsing/common/document.ts, tests/api/response.spec.ts
=> :bug: add missing pages number attribute

src/parsing/custom/listField.ts
=> :wrench: secondary fix for page id in custom builds

docs/custom_v1.md, src/parsing/custom/listField.ts, tests/product/custom/customDocument.spec.ts, tests/product/custom/lineItems.spec.ts
=> :wrench: fix internals linked to custom api uses

docs/bank_account_details_v2.md, docs/bank_check_v1.md, docs/barcode_reader_v1.md, docs/carte_grise_v1.md, docs/carte_vitale_v1.md, docs/code_samples/carte_grise_v1.txt, docs/cropper_v1.md, docs/expense_receipts_v5.md, docs/idcard_fr_v2.md, docs/invoices_v4.md, docs/license_plates_v1.md, docs/multi_receipts_detector_v1.md, docs/passport_v1.md, docs/proof_of_address_v1.md, docs/us_driver_license_v1.md, src/parsing/standard/position.ts, src/product/fr/carteGrise/carteGriseV1.ts, src/product/fr/carteGrise/carteGriseV1Document.ts, src/product/fr/carteGrise/internal.ts, src/product/fr/index.ts, src/product/fr/internal.ts, tests/product/barcodeReader/barcodeReaderV1.spec.ts, tests/product/fr/carteGrise/carteGriseV1.spec.ts, tests/product/us/w9/w9V1.spec.ts
* :sparkles: add support for Carte Grise V1
* :bug: fix empty positions not being created as arrays
* :arrow_up: update testing lib & product docs
=> :sparkles: add support for Carte Grise V1

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: release/v4.4.0

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.6.0

docs/bank_account_details_v2.md, docs/bank_check_v1.md, docs/barcode_reader_v1.md, docs/carte_grise_v1.md, docs/carte_vitale_v1.md, docs/code_samples/default_async.txt, docs/cropper_v1.md, docs/expense_receipts_v5.md, docs/financial_document_v1.md, docs/idcard_fr_v2.md, docs/invoices_v4.md, docs/license_plates_v1.md, docs/multi_receipts_detector_v1.md, docs/passport_v1.md, docs/proof_of_address_v1.md, docs/us_driver_license_v1.md, docs/us_w9_v1.md, src/cli.ts, src/client.ts
=> :arrow_up: update retry counter values for async parsing

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.6.1

example/invoiceSplitterTutorial.js
=> :bug: fix invoice splitter tutorial example file

docs/invoices_v4.md, src/parsing/standard/text.ts, src/product/invoice/invoiceV4Document.ts, tests/fields/classification.spec.ts, tests/fields/date.spec.ts, tests/fields/locale.spec.ts, tests/fields/text.spec.ts, tests/product/invoice/invoiceV4.spec.ts
:arrow_up: update invoices to 4.4
=> :arrow_up: update invoices to 4.4

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.7.0

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.8.0

README.md, docs/code_samples/default_async.txt, docs/generated_v1.md
* :bug: fix default code sample for generated & generic async
* :memo: add generated doc entry in readme file
=> :bug: fix default async code sample

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.8.1

src/cli.ts, src/client.ts, src/parsing/generated/generatedList.ts, tests/product/generated/generatedListField.spec.ts
* :bug: fix improper float parsing in GeneratedListField objects
* :bug: fixed issue causing typescript to force users to set their own value for asynchronous calls options if a custom endpoint was specified
* :arrow_up: add test for floats in generated list fields
=> :bug: fix improper float parsing for GeneratedV1 & update async options

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.8.2

docs/eu_driver_license_v1.md, docs/international_id_v2.md, src/product/eu/driverLicense/driverLicenseV1.ts, src/product/eu/driverLicense/driverLicenseV1Document.ts, src/product/eu/driverLicense/driverLicenseV1Page.ts
=> :memo: fix docs

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.9.0

.eslintrc, src/cli.ts, src/client.ts, src/http/baseEndpoint.ts, src/http/endpoint.ts, src/http/error.ts, src/http/index.ts, src/http/response_validation.ts, src/parsing/common/asyncPredictResponse.ts, src/product/financialDocument/financialDocumentV1LineItem.ts, src/product/fr/bankAccountDetails/bankAccountDetailsV2Bban.ts, src/product/invoice/invoiceV4LineItem.ts, src/product/receipt/receiptV5LineItem.ts, src/product/resume/resumeV1Certificate.ts, src/product/resume/resumeV1Education.ts, src/product/resume/resumeV1Language.ts, src/product/resume/resumeV1ProfessionalExperience.ts, src/product/resume/resumeV1SocialNetworksUrl.ts, tests/api/asyncResponse.spec.ts
* :recycle: update error handling
* :recycle: update spacing rule due to internal inconsistencies
=> :recycle: update error handling

.eslintrc, src/errors/handler.ts, src/errors/index.ts, src/errors/mindeeError.ts, src/http/apiSettings.ts, src/http/endpoint.ts, src/http/index.ts, src/http/responseValidation.ts, src/input/pageOptions.ts, src/internal.ts
* :memo: update some missing documentation
* :bug: fix some namespaces ignored by typedoc
* :recycle: expose more internals
* :recycle: fix non-camel case file names & functions
=> :recycle: update internals & uniformize file naming conventions

src/http/responseValidation.ts, tests/api/asyncResponse.spec.ts
=> :recycle: update new test & update test lib

CHANGELOG.md, docs/international_id_v2.md, package-lock.json, package.json
=> :bookmark: version 4.9.1

docs/invoices_v4.md, src/product/invoice/invoiceV4Document.ts, tests/product/invoice/invoiceV4.spec.ts
=> :sparkles: update Invoice to v4.5

src/http/error.ts, tests/api/endpoint.spec.ts
:bug: fix error handler ignoring codes in two specific cases
Does not directly impact #265, but should help with similar errors in some instances.
=> :bug: fix error management not following intended flow

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.10.0

docs/expense_receipts_v5.md, docs/financial_document_v1.md, src/product/financialDocument/financialDocumentV1Document.ts, src/product/receipt/receiptV5Document.ts, tests/product/receipt/receiptV5.spec.ts
* :sparkles: update receipt API to v5.2
* :sparkles: update financial doc API to 1.7
* :recycle: update test lib
=> :sparkles: update financial document to 1.7 & receipt to 5.2

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.12.0

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.13.0

src/imageOperations/common/extractedImage.ts, src/imageOperations/invoiceSplitterExtractor/extractedInvoiceSplitterImage.ts, src/imageOperations/multiReceiptsExtractor/extractedMultiReceiptImage.ts, src/imageOperations/multiReceiptsExtractor/multiReceiptsExtractor.ts, tests/imageOperations/multiReceiptsExtractor.spec.ts
* :recycle: add test for multipage receipts extractor
* :recycle: fix typos
* :recycle: ExtractedImage is no longer abstract
=> :recycle: add multi-page test for multi-receipts detector

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.13.1

package-lock.json, src/parsing/standard/companyRegistration.ts
* :recycle: add type on company registration print
* :arrow_up: update dependency for braces
=> Update registration field

docs/expense_receipts_v5.md, docs/financial_document_v1.md, docs/invoices_v4.md, docs/us_healthcare_cards_v1.md, src/cli.ts, src/product/financialDocument/financialDocumentV1Document.ts, src/product/financialDocument/financialDocumentV1LineItem.ts, src/product/internationalId/internationalIdV2Document.ts, src/product/invoice/invoiceV4Document.ts, src/product/invoice/invoiceV4LineItem.ts, src/product/multiReceiptsDetector/multiReceiptsDetectorV1Document.ts, src/product/receipt/receiptV5Document.ts, src/product/us/healthcareCard/healthcareCardV1.ts, src/product/us/healthcareCard/healthcareCardV1Copay.ts, src/product/us/healthcareCard/healthcareCardV1Document.ts, src/product/us/healthcareCard/index.ts, src/product/us/index.ts, tests/product/us/healthcareCard/healthcareCardV1.spec.ts
* :sparkles: add support for US healthcare card V1
* :sparkles: add support for Invoice V4.7
* :sparkles: add support for FinancialDocument V1.9
* :recycle: update CLI entry & re-order product references
=> :sparkles: add support for us healthcare card & us mail, update invoices & financial document.

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.14.0

.github/workflows/sync-readme.yml, README.md, docs/bank_account_details_v2.md, docs/bank_check_v1.md, docs/barcode_reader_v1.md, docs/carte_grise_v1.md, docs/carte_vitale_v1.md, docs/cropper_v1.md, docs/custom_v1.md, docs/eu_driver_license_v1.md, docs/expense_receipts_v5.md, docs/financial_document_v1.md, docs/generated_v1.md, docs/getting_started.md, docs/idcard_fr_v2.md, docs/international_id_v2.md, docs/invoice_splitter_v1.md, docs/invoices_v4.md, docs/license_plates_v1.md, docs/multi_receipts_detector_v1.md, docs/passport_v1.md, docs/proof_of_address_v1.md, docs/resume_v1.md, docs/us_driver_license_v1.md, docs/us_healthcare_cards_v1.md, docs/us_mail_v2.md, docs/us_w9_v1.md
=> :memo: update md documentation + add auto-sync action

package-lock.json, package.json
Update npm dependencies to cover vulnerability.
=> :arrow_up: update dependencies

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.14.1

src/parsing/common/document.ts, src/parsing/common/extras/extras.ts, src/parsing/common/extras/fullTextOcrExtra.ts, src/parsing/common/extras/index.ts, src/parsing/common/index.ts, src/parsing/common/page.ts, tests/extras/fullTextOcr.spec.ts
=> :sparkles: add support for full text OCR extraction

src/input/localResponse.ts, tests/inputs/localResponse.spec.ts
=> :recycle: add missing tests for localresponse

.github/workflows/test-code-samples.yml, .github/workflows/test-integration.yml, .github/workflows/test.yml, package.json, src/client.ts, src/http/endpoint.ts, src/parsing/common/page.ts, tests/extras/extras.integration.ts
* :bug: fix extra parameters in calls being improperly evaluated
* :bug: fix full_text_ocr extra being missing
* :recycle: add integration testing
=> :bug: fix improper extra handling & add integration tests

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: version 4.15.0

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.16.0

example/invoiceSplitterCustomSplitsTutorial.js, example/invoiceSplitterTutorial.js, example/multiReceiptsTutorial.js, tests/imageOperations/invoiceSplitter.integration.ts, tests/testingUtilities.ts
* :recycle: add integration test for auto-invoice splitter utility
* :recycle: update test lib
* :memo: update example scripts
=> :recycle: update integration tests & example scripts

docs/bill_of_lading_v1.md, docs/energy_bill_fra_v1.md, docs/expense_receipts_v5.md, docs/financial_document_v1.md, docs/invoices_v4.md, docs/nutrition_facts_v1.md, docs/payslip_fra_v2.md, docs/us_mail_v2.md, src/parsing/standard/date.ts, src/product/financialDocument/financialDocumentV1Document.ts, src/product/invoice/invoiceV4Document.ts, tests/extras/extras.integration.ts, tests/fields/date.spec.ts, tests/product/invoice/invoiceV4.spec.ts
=> :sparkles: add support for financial document v1.10 & invoice v4.8

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.17.0

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.17.1

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.18.0

package-lock.json, src/parsing/common/page.ts
* :bug: fix composed API server response not properly filling full_text_ocr in pages
* :arrow_up: update dependencies
=> :bug: fix composed API server response not properly filling full_text_ocr in pages

src/http/endpoint.ts, src/http/error.ts, src/http/responseValidation.ts, tests/api/endpoint.spec.ts
=> :bug: fix some errors defaulting to 500 when they should be deserialized properly

.github/workflows/test-integration.yml, docs/code_samples/workflow_execution.txt, src/client.ts, src/http/baseEndpoint.ts, src/http/endpoint.ts, src/http/httpParams.ts, src/http/index.ts, src/http/workflowEndpoint.ts, src/parsing/common/asyncPredictResponse.ts, src/parsing/common/execution.ts, src/parsing/common/executionFile.ts, src/parsing/common/executionPriority.ts, src/parsing/common/index.ts, src/parsing/common/workflowResponse.ts, tests/test_code_samples.sh, tests/workflows/workflow.integration.ts, tests/workflows/workflow.spec.ts
=> :sparkles: add support for workflows

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.20.0

README.md, src/input/sources/urlInput.ts, tests/inputs/sources.spec.ts, tests/inputs/urlInputSource.integration.ts, tests/inputs/urlInputSource.spec.ts
=> :sparkles: add support for remote resource fetching

CHANGELOG.md, README.md, docs/custom_v1.md, docs/getting_started.md, package-lock.json, package.json
=> :bookmark: Version 4.21.0

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.22.0

src/parsing/common/asyncPredictResponse.ts, tests/inputs/localResponse.spec.ts
=> :bug: add missing 'failed' value to jobs

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.23.1

docs/energy_bill_fra_v1.md, src/cliProducts.ts, src/product/fr/energyBill/energyBillV1Document.ts, src/product/fr/energyBill/energyBillV1EnergyUsage.ts, src/product/fr/energyBill/energyBillV1MeterDetail.ts, src/product/us/healthcareCard/healthcareCardV1Document.ts
=> :sparkles: bump FR EnergyBillV1 to V1.2 & US HealthcareCardV1 to V1.1

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.24.0

src/parsing/common/document.ts, src/parsing/common/page.ts
=> :bug: fix null objects being returned in extras

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.24.1

docs/financial_document_v1.md, docs/invoices_v4.md, docs/us_healthcare_cards_v1.md, src/product/financialDocument/financialDocumentV1Document.ts, src/product/invoice/invoiceV4Document.ts, src/product/us/healthcareCard/healthcareCardV1Copay.ts, src/product/us/healthcareCard/healthcareCardV1Document.ts, tests/product/financialDocument/financialDocumentV1.spec.ts, tests/product/us/healthcareCard/healthcareCardV1.spec.ts
=> :sparkles: add support for Findoc V1.12, Invoices V4.10, US Healthcare Cards V1.2

package-lock.json, package.json
Bump mocha dependency to cover glob & inflect deprecation
=> :arrow_up: bump mocha dependency

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.25.0

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.26.0

src/client.ts, src/http/endpoint.ts, src/http/httpParams.ts, src/http/workflowEndpoint.ts, src/parsing/common/document.ts, src/parsing/common/extras/fullTextOcrExtra.ts, src/parsing/common/extras/ragExtra.ts, src/parsing/common/inference.ts, src/pdf/pdfCompressor.ts, tests/inputs/sources.spec.ts, tests/workflows/workflow.integration.ts
* :sparkles: add support for RAG polling
* :sparkles: add extras accessor from inference
* :bug: fix improper deserialization of extras in some instances
=> :sparkles: add support for workflow polling

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.28.0

tests/extras/extras.integration.ts, tests/workflows/workflow.integration.ts
=> :white_check_mark: add mvision tests

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.29.0-rc1

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.29.0-rc3

src/parsing/v2/field/inferenceFields.ts, src/parsing/v2/field/simpleField.ts, src/parsing/v2/index.ts, src/parsing/v2/inference.ts, src/parsing/v2/inferenceFile.ts, src/parsing/v2/inferenceModel.ts, src/parsing/v2/job.ts, tests/parsing/v2/inference.spec.ts
+ upgrade tests & toString() displays
=> :recycle: upgrade field syntaxes to match other SDKs

src/index.ts, tests/v2/clientV2.integration.ts, tests/v2/clientV2.spec.ts
Make it easier to use input sources directly.
=> :recycle: allow direct import of input sources

CHANGELOG.md, package-lock.json, package.json
=> :bookmark: Version 4.30.0
