mindee/mindee-api-nodejs

- README.md
- examples/financialDocument.js
- examples/invoice.js
- examples/receipt.js
- mindee/api/financialDocument.js
- mindee/api/invoice.js
- mindee/api/receipt.js
Before this PR, the parse function asked multiples parameters to work with no specific name.
With this, we ask now for an object for easier use.
- Change all parse functions in Api Objects to use an object instead of multiple parameters
- Rename file parameter for input to be easier to understand
This is an amelioration asked from our users to have an easier time with the SDK
- Run unit tests
- Run examples from SDK
> Change parse function to use an object instead of multiples parameters

- README.md
- examples/financialDocument.js
- examples/invoice.js
- examples/receipt.js
- mindee/api/financialDocument.js
- mindee/api/invoice.js
- mindee/api/receipt.js
- mindee/api/request.js
- mindee/inputs.js
- Add a parameter `filename` that let you choose the filename of the document
- Set a default filename for streams (named `stream`) to fix issue with duplex streams
- Add a default filename `stream` to streams
- Add a filename parameter that is used to replace filename by default in streams and files (this is not used with base64 data)
- Use this filename in form-data in requests to the API with streams
Fix an issue with duplex streams not working with the SDK
- running unit tests
- running examples
- tested with an example from the user that was not working before the fix ([see this repository](https://github.com/fraxken/mindee_stream_repro))
> Add a parameter filename and a default filename for steams

- examples/documents/invoices/credit_note.pdf
- examples/invoice.js
- mindee/api/invoice.js
Invoices now return the type of document from the api 
- Invoices now return the type of document from the api if possible (can be `credit note`or `invoice`). If not here, it still return "invoice"
- An example with a credit note has been added to see this update
- Unit tests has been run
- The examples are still working
> Invoices : Document type from API

- mindee/api/financialDocument.js
- mindee/api/invoice.js
- mindee/api/receipt.js
cutPdf parameters form `parse` methods wasn't sent to the Input class the right way.
Specifically describe the parameters sent for creating Input objects in `parse` methods from Receipt, Invoice, and FinancialDocument API classes.
> fix: :bug: Updated api Input initialization to specifically declare parameters

- CHANGELOG.md
- mindee/documents/document.js
- package.json
This PR should fix the issue about the Invoice object on API response that doesn't return the array of taxes.
Given a document of two pages, the invoice API result should contains an object of prediction for each page which will later be merged in on single response sent by the SDK to the user using the `invoice` attribute in this case. The issue come from the function `MergePages` that don't take into account the attributes of type array like `taxes`.
```
static mergePages(documents) {
const finalDocument = documents[0].clone();
const attributes = Object.getOwnPropertyNames(finalDocument);
for (const document of documents) {
for (const attribute of attributes) {
if (
document?.[attribute]?.probability >
finalDocument[attribute].probability
) {
finalDocument[attribute] = …
```
> fix: 🐛 handle attribute of type array when merging pages

- CHANGELOG.md
- package-lock.json
- package.json
Get words values when includeWords parameter is true
Since v1.1.0, the parameter includeWords is not interpreted and its value is never returned by the client library
> chg: 📝 prepare v1.2.0

- .github/workflows/linting.yml
- .github/workflows/test.yml
- README.md
- mindee/api/request.js
- mindee/inputs.js
When working with streams or base 64 encoded strings:
* Allow the user to send the file name, if set, use this to determine file type based on the extension.
* If the file name is not set, generate a file name based on the detected MIME type.
* If we can't determine the MIME type (for a corrupt or non-standard file for example), force the user to set the filename when calling the `parse` function.
Currently there is no recourse for a user if the stream contents cannot be used to determine the MIME type.
> Always send the file name to the API.

- mindee/api/request.js
The old code was sending errors to stdout which make hard to detect issues when API request are failing (logs are not where we expect them).
Running `npm test` (by the way some tests fail on Windows.. related to pdf cut).
> 🐛 forward api error to stderr instead of stdout

- mindee/inputs.js
The old code was always working with the same limit of pages for a pdf document (which was a limit a 5 pages). Because of that the client library was loosing datas from the API response when the pdf had more than 5 pages. If the data was discovered in only one page, the client library would never get it because the asynchronous processing would catch the empty values first.
Running `npm test` (by the way some tests fail on Windows.. related to pdf cut).
> 🐛 use pdf length instead of cut pdf size limit

- CHANGELOG.md
- mindee/api/request.js
- package-lock.json
- package.json
The issue was that some errors were detected but the script wouldn't stop. Because the error was printed instead rejected inside the promise.
Running `npm test`.
> 🐛 reject error instead of only print it

- mindee/errors/handler.js
- mindee/index.js
- mindee/inputs.js
- mindee/logger.js
When a PDF has more than 3 pages, but is encrypted.
* better to send the encrypted PDF as-is rather than risk corrupting it
* log an error mentioning we couldn't cut the PDF
* the server will count the pages and possibly return an error (depends on the endpoint's settings), this will be caught by the client
#64 
Tested with sample files from a customer.
> Fix encrypted PDF

- src/api/endpoint.ts
- src/api/index.ts
- src/api/response.ts
- src/cli.ts
- src/client.ts
- src/constants.ts
- src/documents/cropper.ts
- src/documents/custom.ts
- src/documents/document.ts
- src/documents/documentConfig.ts
- src/documents/financialDocument.ts
- src/documents/index.ts
- src/documents/invoice.ts
- src/documents/passport.ts
- src/documents/receipt.ts
- src/fields/cropper.ts
- src/fields/field.ts
- src/fields/index.ts
- src/fields/orientation.ts
- src/index.ts
- tests/apiPaths.ts
- tests/documents/cropper.spec.ts
- tests/documents/customDocument.spec.ts
- tests/documents/financialDocument.spec.ts
- tests/documents/invoice.spec.ts
- tests/documents/receipt.spec.ts
- tests/fields/cropper.spec.ts
- tests/fields/orientation.spec.ts
Add the cropper as a stand-alone endpoint and as extra information in the predict API.
This required changing the orientation field from specific to Invoice and Receipt, to now being available for all products.
Added basic unit tests
> Add cropper endpoint and feature

- README.md
- docs/code_samples/custom_v1.txt
- src/cli.ts
- src/client.ts
- :arrow_up: moved all variables except product type and input into a `params` object to simplify syntax
- :sparkles: added option to create custom endpoint before parsing
- :recycle: tweaked cli to match those changes
> :recycle: simplified syntax for predict parameters

- .github/workflows/test.yml
Looks like installing the latest npm version breaks things on node 16 now.
> :construction_worker: don't install the latest version of npm

- src/parsing/custom/index.ts
- src/parsing/custom/lineItems.ts
- src/product/custom/customV1Document.ts
- src/product/custom/customV1Page.ts
Make sure to use the line tolerance when calculating fields, otherwise some fields are omitted.
When writing the tutorial.
> :bug: take line height tolerance into account when evaluating fields

- src/parsing/custom/listField.ts
* :bug: current version of custom build has changed the `page_id` position for candidates, causing CustomV1 product to lose the property per field. This fixes it.
* :recycle: marked page_id as optional to account for this change
> :bug: fix page id syntax to account for newer syntax

- src/errors/handler.ts
- src/input/sources.ts
- src/parsing/generated/generatedObject.ts
* :black_flag: marked the `errorHandler` class as deprecated
* :recycle: tweaked url error handling to prevent them from being sent to the server.
#265
> :recycle: deprecate old error handler

- src/client.ts
- src/index.ts
- src/input/index.ts
- src/input/localResponse.ts
- tests/inputs/localResponse.spec.ts
* :sparkles: add support for local response loading
* :sparkles: add support for HMAC validation (for webhooks)
> :sparkles: add support for local responses, webhooks & HMAC signature

- src/pdf/pdfOperation.ts
- tests/pdf/pdfOperation.spec.ts
* :bug: fix onMinPages threshold ignored when page operations are longer than the file pages
* :recycle: fix test that was supposed to test for this
#296
> :bug: fix page operations not taking minimum threshold into account

- docs/code_samples/workflow_polling.txt
- src/client.ts
- src/http/endpoint.ts
- tests/test_code_samples.sh
* :bug: fix workflow polling not working in some instances
* :memo: add sample code for workflow polling
> :bug: fix workflow polling not working in some instances

- docs/code_samples/workflow_ots_rag.txt
Add RAG sample code for OTS products.
> :memo: add RAG sample code for OTS products

- package-lock.json
- package.json
- src/imageOperations/common/imageExtractor.ts
- src/imageOperations/invoiceSplitterExtractor/invoiceSplitterExtractor.ts
- src/imageOperations/multiReceiptsExtractor/multiReceiptsExtractor.ts
- src/pdf/pdfCompressor.ts
- src/pdf/pdfOperation.ts
- tests/pdf/pdfTypes.spec.ts
> :bug: fix default-encrypted & XFA pdfs not opening

- .github/workflows/_test-integrations.yml
- package-lock.json
- src/clientV2.ts
- src/http/mindeeApiV2.ts
- src/input/sources/urlInput.ts
- src/parsing/v2/field/baseField.ts
- src/parsing/v2/field/dynamicField.ts
- src/parsing/v2/field/objectField.ts
- src/parsing/v2/field/simpleField.ts
- tests/v2/clientV2.integration.ts
* :recycle: change V2 field internals to match other SDKs
> :sparkles: add support for URL inputs in V2 + bump dependencies

- .github/workflows/_test-code-samples.yml
- .github/workflows/_test-units.yml
- src/client.ts
- src/clientV2.ts
- src/index.ts
- src/input/localResponse.ts
- src/input/sources/base64Input.ts
- src/input/sources/bufferInput.ts
- src/input/sources/bytesInput.ts
- src/input/sources/inputSource.ts
- src/input/sources/localInputSource.ts
- src/input/sources/pathInput.ts
- src/input/sources/streamInput.ts
- src/input/sources/urlInput.ts
- src/parsing/v2/field/fieldConfidence.ts
- tests/inputs/localResponse.spec.ts
- tests/inputs/pageOperations.spec.ts
- tests/inputs/sources.spec.ts
- tests/parsing/v2/inference.spec.ts
- tests/v2/clientV2.spec.ts
* do not permit using the mindee client to load sources
* try not to break anything while automatically running the `init()` method as needed
* confidence score enum values should be capitalized
* adjust some tests around confidence score
> :recycle: adjust for RC-6

- src/parsing/v2/field/simpleField.ts
- tests/parsing/v2/inference.spec.ts
Harmonize with other typed languages.
> :sparkles: add typed value accessors
